### ISSUE TITLE
Promise.done is deprecated.

### ISSUE THREAD

**Issue by jmbuytaert** [atom-compare-files/atom-compare-files#49]
Atom now uses ES6 Promises instead of Q. Call promise.then instead of promise.done
```
Promise.done (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1214:5)
atom-workspace.compare (/Users/jbuytaer/.atom/packages/compare-files/lib/compare-files.js:81:11)
CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1181:28)
```

**Comment by ParitoshBh** [comment]
There's a pull request #51 taking care of this.

**Comment by ParitoshBh** [comment]
Pull request merged. Closing this issue.

**Comment by danbrennerarc** [comment]
Still happening:

Atom now uses ES6 Promises instead of Q. Call promise.then instead of promise.done
Report Issue
Promise.done - <embedded>:1661:11
atom-workspace.compare - C:\Users\dan.brenner\.atom\packages\compare-files\lib\compare-files.js:81:11
CommandRegistry.handleCommandEvent - <embedded>:18816:35
handleCommandEvent - <embedded>:18554:65
CommandRegistry.dispatch - <embedded>:18717:25
AtomEnvironment.dispatchApplicationMenuCommand - <embedded>:1553:34

**Comment by mpiaria** [comment]
I saw the same issue today:

Atom now uses ES6 Promises instead of Q. Call promise.then instead of promise.done
Report Issue
Promise.done - <embedded>:1661:11
atom-workspace.compare - C:\Users\Michael\.atom\packages\compare-files\lib\compare-files.js:81:11
CommandRegistry.handleCommandEvent - <embedded>:18816:35
handleCommandEvent - <embedded>:18554:65
CommandRegistry.dispatch - <embedded>:18717:25
AtomEnvironment.dispatchApplicationMenuCommand - <embedded>:1553:34

**Comment by ParitoshBh** [comment]
Published a new plugin update. This issue should now be resolved.
